// src/theme/icons.js
export {
    CheckCircle,
    XCircle,
    ArrowLeft,
    ArrowRight,
    Lightning,
    CalendarPlus,
    MagnifyingGlass,
    ChatCircle,
    Sun,
    Moon,
    Plus,
    CloudSun,
    SunHorizon, 
    UserCircle,
    Envelope,
    Bell,
    Password,
    NotePencil,
    Heartbeat,
    AddressBook,
    Briefcase,
    Notification,
    MessengerLogo,
    File,
    Books,
    Gift,
    Buildings,
    CaretDown,
    MagnifyingGlassPlus,

  } from 'phosphor-react';