name: Frontend CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Lint
        run: npm run lint || echo "Lint fallido (pero no rompe el CI aún)"

      # No hay build, solo validamos que lint pase por ahora
